default:
  image: "hugomods/hugo:exts"

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  HUGO_ENVIRONMENT: production
  HUGO_ENV: production
  HUGO_FLAGS: "--gc --minify"

test:
  script:
    - apk add --no-cache pandoc make
    - make build
  rules:
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH

create-pages:
  script:
    - apk add --no-cache pandoc make
    - make build
  pages: true
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  environment: production